image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - cp -r .* .public || true
  artifacts:
    paths:
      - .public
  only:
    - main
